export const Player = {
  GetPlayers: "player/get_players",
  GetPlayerInfo: "player/get_player_info",
  GetPlayState: "player/get_play_state",
  SetPlayState: "player/set_play_state",
  GetNowPlayingMedia: "player/get_now_playing_media",
  GetVolume: "player/get_volume",
  SetVolume: "player/set_volume",
  VolumeUp: "player/volume_up",
  VolumeDown: "player/volume_down",
  GetMute: "player/get_mute",
  SetMute: "player/set_mute",
  ToggleMute: "player/toggle_mute",
  GetPlayMode: "player/get_play_mode",
  SetPlayMode: "player/ste_play_mode",
  GetQueue: "player/get_queue",
  PlayQueue: "player/play_queue",
  RemoveFromQueue: "player/remove_from_queue",
  SaveQueue: "player/save_queue",
  ClearQueue: "player/clear_queue",
  MoveQueueItem: "player/move_queue_item",
  PlayNext: "player/play_next",
  PlayPrevious: "player/play_previous",
  SetQuickselect: "player/set_quickselect",
  PlayQuickselect: "player/play_quickselect",
  GetQuickselects: "player/get_quickselects",
  CheckUpdate: "player/check_update",
} as const;

export type Player = (typeof Player)[keyof typeof Player];
